[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install --assume-yes libssl-dev",
    "export OPENSSL_ROOT_DIR=/usr",
]

[target.aarch64-unknown-linux-gnu]
# [build.env]
# passthrough = ["CMAKE_TOOLCHAIN_FILE_aarch64_unknown_linux_gnu"]

[build.env]
passthrough = ["CMAKE_TOOLCHAIN_FILE_aarch64_unknown_linux_musl"]
