# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

[build.env]
# This overrides the CMake toolchain file that Cross natively wants to use,
# since it causes problems with the vendored OpenSSL version that Paho wants to use
passthrough = [
    "CMAKE_TOOLCHAIN_FILE_aarch64_unknown_linux_musl",
    "CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_musl",
]
