FROM --platform=linux/amd64 debian:bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV RUST_LOG=trace

RUN apt-get update && apt-get install -y \
    libc6 \
    libgcc-s1 \
    libstdc++6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY target/x86_64-unknown-linux-gnu/release/zenoh_mqtt /app/zenoh_mqtt

RUN chmod +x /app/zenoh_mqtt

EXPOSE 7447
EXPOSE 1883

CMD ["./zenoh_mqtt", "--config", "config/CONFIG.json5"]
